services:
  mongo:
    container_name: mongo
    restart: always
    hostname: mongo
    image: mongo
    volumes:
      - mongodb_me:/data/db
    ports:
      - "7294:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: 123ahhahah
      MONGO_INITDB_ROOT_PASSWORD: 111qeqwe
  server:
    build: backend/
    ports:
      - "7293:7293"
    links:
      - mongo
  client:
    build: frontend/
    ports: 
      - "7292:7292"
    depends_on:
      - server
volumes:
  mongodb_me: