version: "3"
services:
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
      - "27017:7294"
  server:
    build: backend/
    ports:
      - "7293:7293"
    links:
      - mongo
  client:
    build: frontend/
    ports: 
      - "7292:7292"
    depends_on:
      - server