name: Build and Deploy
on: [push]
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to master
      - uses: actions/checkout@v3

      - name: Setup NodeJS
      - uses: actions/setup-node@v3
        with:
          node-version: 20
        working-directory: ./backend
      - run: |
          npm ci
          
      - name: Connect via SSH and Deploy
      - uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /home/mukhin/lrng-fullstack
            git  pull
            docker compose down
            docker compose up -d --build